language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
before_install:
  - pip install pipenv
  - python -m pipenv.help || true
install:
  - pipenv install --verbose
script:
  - true
